import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  cardContainer: {
    padding: 0,
    backgroundColor: "#ffffff",
    borderRadius: 9,
    borderBottomColor: "#ffffff",
    borderWidth: 0.5,
    marginBottom: -10,
    shadowColor: "rgba(0, 0, 0, 0.08)",
    shadowOffset: {
      width: 0,
      height: 15,
    },
    shadowRadius: 25,
    shadowOpacity: 1,
  },

  cardTitleStyle: {
    color: "#1c1c1c",
    fontFamily: "HelveticaNeue",
    fontWeight: "normal",
    fontStyle: "normal",
    letterSpacing: 0,
    marginTop: -10,
    fontSize: 16,
    textTransform: "uppercase",
  },
  subTitleStyle: {
    color: "#be4020",
    fontFamily: "HelveticaNeue",
    fontWeight: "normal",
    fontStyle: "normal",
    letterSpacing: 0,
    marginTop: 8,
    fontSize: 14,
  },
  listContainer: {
    backgroundColor: "#ffffff",
    borderTopLeftRadius: 9,
    borderTopRightRadius: 9,
    borderBottomColor: "#ffffff",
    borderWidth: 0,
    shadowColor: "rgba(0, 0, 0, 0.08)",
    shadowOffset: {
      width: 0,
      height: 15,
    },
    shadowRadius: 25,
    shadowOpacity: 1,
    marginTop: -20,
  },

  bottomView: {
    backgroundColor: "#ffffff",
    padding: 0,
    paddingLeft: 20,
    paddingRight: 10,
    marginBottom: 10,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  nmby_txt: {
    color: "#9b9b9b",
    fontFamily: "HelveticaNeue",
    fontSize: 15,
    fontWeight: "normal",
    fontStyle: "normal",
    lineHeight: 20,
    letterSpacing: 0.75,
    flexWrap: "wrap",
    flex: 2.5,
  },
  nmby_title: {
    color: "#19537e",
    fontFamily: "HelveticaNeue",
    fontSize: 15,
    fontWeight: "normal",
    fontStyle: "normal",
    lineHeight: 20,
    letterSpacing: 0.75,
  },
  nmby_dt: {
    color: "#9c9c9c",
    fontFamily: "HelveticaNeue",
    fontSize: 13,
    fontWeight: "normal",
    fontStyle: "normal",
    lineHeight: 20,
    letterSpacing: 0.75,
    flexWrap: "wrap",
    flex: 1,
    textAlign: "right",
  },
  nmtr_text: {
    color: "#be4020",
    fontFamily: "HelveticaNeue",
    fontSize: 14,
    fontWeight: "normal",
    fontStyle: "normal",
    lineHeight: 20,
    letterSpacing: 0.75,
  },
  closeButtonStyle: {
    alignSelf: "flex-end",
    zIndex: 1,
    top: 5,
    right: 10,
  },
});

export default styles;
